### ISSUE TITLE
Binary dependent on hard coded data path

### ISSUE THREAD

**Issue by rmarronnier** [watzon/cadmium#12] opened 2019-07-08 20:58 UTC
Great job job on this fantastic lib !

I'm developing a web app deployed on Heroku and after the crystal binary is compiled all librairies / shards are discarded.

My app compiles fine with cadmium but crashes because it can't find files inside the data folder : 
```
2019-07-08T20:22:33.238998+00:00 app[web.1]: Unhandled exception: Error opening file '/tmp/build_b996c138b6ca4a4c639a8e6ba2a58942/lib/cadmium/src/cadmium/../../data/sentiment.txt' with mode 'r': No such file or directory (Errno)
2019-07-08T20:22:33.239028+00:00 app[web.1]: from /tmp/crystal/share/crystal/src/crystal/system/file.cr:7:7 in 'new'
2019-07-08T20:22:33.239031+00:00 app[web.1]: from /tmp/crystal/share/crystal/src/file.cr:591:12 in 'read'
2019-07-08T20:22:33.239033+00:00 app[web.1]: from /tmp/crystal/share/crystal/src/path.cr:102:5 in '__crystal_main'
2019-07-08T20:22:33.239036+00:00 app[web.1]: from /tmp/crystal/share/crystal/src/crystal/main.cr:47:14 in 'main'
2019-07-08T20:22:33.239038+00:00 app[web.1]: from /tmp/crystal/share/crystal/src/hash.cr:63:3 in '__libc_start_main'
2019-07-08T20:22:33.239040+00:00 app[web.1]: from _start
2019-07-08T20:22:33.239042+00:00 app[web.1]: from ???
```

Should binaries compiled against Cadmium be dependent on Cadmium being present on the target computer ?

I think not, but there are several solutions to this problem : 

1 - Put all data inside .cr files in arrays / hashes / tuples

2 - Make the path to data files configurable (via a yml config file or ENV variables)

3 - ??? I can't think of more :-)

If I missed something in the docs, feel free to close this issue ;-)

**Comment by watzon** [comment] 2019-07-08 21:00
Ahh I know the problem. The problem isn't that the path is hardcoded so much as it is that the file isn't being loaded into the binary like I thought it was. Should be an easy fix, so I'll get back to you soon.

**Comment by rmarronnier** [comment] 2019-07-08 21:10
Wow, that was fast ! Thanks :-D

**Comment by watzon** [comment] 2019-07-08 21:14
I try! So currently files are being read in as Strings, I just need to make it so they get read in as StringLiterals using the `read_file` macro. I should have it fixed by this evening.

**Comment by rmarronnier** [comment] 2019-07-08 21:24
Yeah, I saw the gitter chat :-) No stress mate. I'm heading for bed now. But I'll sure be telling this tale (in an article or to my grand children) of how crazy fast this bug was fixed :-p

**Closed as completed** 2019-07-09 00:59 UTC

**Comment by watzon** [comment] 2019-07-09 01:04
Should be all good now. I also added the ability to [set custom sentiment data](https://github.com/watzon/cadmium/blob/master/src/cadmium/sentiment.cr#L38) just in case you want to use your own.

**Comment by rmarronnier** [comment] 2019-07-09 11:15
I tried compiling again, and now it fails on compilation with the same error : 
```
in lib/cadmium/src/cadmium/sentiment.cr:42: Error opening file './data/sentiment.txt' with mode 'r': No such file or directory

      @@data ||= {{ read_file("./data/sentiment.txt") }}
```
You can try a 
``` 
crystal spec
```

It seems you made a typo in the data path : 
```crystal
@@data ||= {{ read_file("./data/sentiment.txt") }}
```
Instead of the old one : 
```crystal
@@data = File.read(File.join(__DIR__, "../../data/sentiment.txt"))
```

**Comment by rmarronnier** [comment] 2019-07-09 16:27
```crystal
@@data ||= {{ read_file("#{__DIR__}/../../data/sentiment.txt") }}
```
This works. Do you want me to do a PR ?

**Comment by watzon** [comment] 2019-07-09 17:38
@rmarronnier yes please. I thought removing the `__DIR__` would be fine, but I forgot that when you include Cadmium in another project your cwd changes.
